# ... (rest of your basic-blog-template.rb) ...

  # ==== Grab admin credentials ====
  admin_name = ask("What is your name?", :green).presence || 'Admin'
  admin_email = ask("Enter initial admin email (e.g., admin@example.com):", :green).presence || 'admin@example.com'
  admin_password = ask("Enter initial admin password (min 6 characters):", :green, echo: false).presence || 'password'
  say "\n"

  # --- Start Appending to db/seeds.rb ---
  say "#{INDENT}Adding initial admin user, categories, and featured post to seeds.rb...", :blue

  append_to_file 'db/seeds.rb', <<~RUBY
    # This file is automatically generated by the blog template.
    # It sets up initial admin users, categories, and a featured post.

    # 1. Create Initial Admin User
    Admin.find_or_create_by!(email: '#{admin_email}') do |admin|
      admin.password = '#{admin_password}'
      admin.password_confirmation = '#{admin_password}'
      admin.name = '#{admin_name}'
      admin.title = 'Site Administrator'
      admin.bio = 'The primary administrator of this blog.'

      avatar_path = Rails.root.join('app', 'assets', 'images', 'profile.png')

      if File.exist?(avatar_path) && !admin.avatar.attached?
        admin.avatar.attach(io: File.open(avatar_path), filename: 'profile.png', content_type: 'image/png')
      end
    end
    # Retrieve the admin we just created or found
    admin = Admin.find_by!(email: '#{admin_email}')


    # 2. Seed Initial Categories
    Category.find_or_create_by(category_name: 'Uncategorized') do |category|
      category.category_description = 'Posts that do not have a category'
    end

    Category.find_or_create_by(category_name: 'General') do |category|
      category.category_description = 'General blog posts and updates'
    end

    # Retrieve the categories we just created or found
    uncategorized = Category.find_by!(category_name: 'Uncategorized')
    general = Category.find_by!(category_name: 'General')


    # 3. Seed a Featured Post
    # Ensure only one post is featured by setting others to false if they exist
    Post.where(featured: true).update_all(featured: false)

    featured_post_title = "Welcome to Your New Blog! This is a Featured Article."
    featured_post = Post.find_or_initialize_by(title: featured_post_title)

    featured_post.assign_attributes(
      subtitle: "A quick guide to getting started with your new Rails blog template.",
      published_at: 2.days.ago, # Ensures it's published and visible
      admin: admin, # Use the 'admin' variable safely defined above
      meta_description: "This is your first featured blog post, designed to introduce the capabilities of your new Rails blog. Explore how to create, manage, and publish articles.",
      keywords: ["Rails blog", "template", "getting started", "featured post"],
      featured: true # Mark as featured
    )

    # Action Text Content (HTML format)
    featured_post.content = <<~HTML
      <h1>Hello, World! Welcome to Your Blog.</h1>
      <p>This is your very first blog post, automatically generated by your new Rails blog template. It's designed to give you a quick overview of what's possible.</p>
      <p>You can use the rich text editor in the admin panel to:</p>
      <ul>
        <li>Create beautifully formatted articles with <strong>bold</strong> and <em>italic</em> text.</li>
        <li>Add ordered and unordered lists.</li>
        <li>Embed images and videos seamlessly.</li>
        <li>Insert links: <a href="https://rubyonrails.org/" target="_blank">Ruby on Rails Official Site</a></li>
      </ul>
      <p>This article is set as "featured," meaning it will appear prominently on your blog's homepage. You can easily change which article is featured from your admin dashboard.</p>
      <p>Don't forget to explore the admin dashboard where you can:</p>
      <ul>
        <li>Create new posts and manage existing ones.</li>
        <li>Manage categories for your articles.</li>
        <li>Update your administrator profile.</li>
      </ul>
      <p>We hope you enjoy building and sharing your thoughts with your new blog!</p>
      <p>Happy blogging!</p>
    HTML

    # Attach images using Active Storage
    # These paths assume the images were copied to app/assets/images by the template earlier
    post_image_path = Rails.root.join('app', 'assets', 'images', 'railamellon.jpg')
    meta_image_path = Rails.root.join('app', 'assets', 'images', 'meta-railamellon.jpg')

    # Only attach if the file exists and the attachment isn't already there (for idempotency)
    if File.exist?(post_image_path) && !featured_post.image.attached?
      featured_post.image.attach(io: File.open(post_image_path), filename: 'railamellon.jpg', content_type: 'image/jpeg')
    end
    if File.exist?(meta_image_path) && !featured_post.meta_image.attached?
      featured_post.meta_image.attach(io: File.open(meta_image_path), filename: 'meta-railamellon.jpg', content_type: 'image/jpeg')
    end

    if featured_post.save
      puts "  ✅ Featured Post '\#{featured_post.title}' seeded successfully." # <--- escaped #
      # Assign categories using the has_many :through association
      featured_post.categories << general unless featured_post.categories.include?(general)
      featured_post.categories << uncategorized unless featured_post.categories.include?(uncategorized)
    else
      puts "  ❌ Failed to seed Featured Post: \#{featured_post.errors.full_messages.to_sentence}" # <--- escaped #
    end

    # 4. Seed Additional Non-Featured Posts
    puts "\nSeeding additional non-featured posts..."

    # Post 2
    post_title_2 = "Understanding Rails Migrations"
    post_2 = Post.find_or_initialize_by(title: post_title_2)

    post_2.assign_attributes(
      subtitle: "A deep dive into how Rails handles database schema changes.",
      published_at: 3.days.ago, # A bit older than the featured post
      admin: admin,
      meta_description: "Learn the fundamentals of Rails migrations, how they work, and best practices for managing your database schema evolution.",
      keywords: ["Rails", "migrations", "database", "schema", "ActiveRecord"],
      featured: false # NOT featured
    )
    post_2.content = <<~HTML
      <h2>What are Rails Migrations?</h2>
      <p>Rails migrations are a feature of Active Record that allows you to evolve your database schema over time. Instead of writing SQL directly, you use Ruby to describe your changes.</p>
      <h3>Why Use Migrations?</h3>
      <p>Migrations provide a structured and version-controlled way to manage your database:</p>
      <ul>
        <li><strong>Collaboration:</strong> Multiple developers can work on the same database schema changes without conflicts.</li>
        <li><strong>Consistency:</b> Ensures that all development, staging, and production environments have the same schema.</li>
        <li><strong>Rollbacks:</b> Easy to undo changes if something goes wrong.</li>
      </ul>
      <p>This post is an example of a regular blog entry.</p>
    HTML

    # Attach images if desired (optional for non-featured posts)
    # Ensure you copy 'sample_post_image2.jpg' in your template's assets section.
    post_image_path_2 = Rails.root.join('app', 'assets', 'images', 'red-rails.jpg')

    if File.exist?(post_image_path_2) && !post_2.image.attached?
      post_2.image.attach(io: File.open(post_image_path_2), filename: 'red-rails.jpg', content_type: 'image/jpeg')
    end

    if post_2.save # Now save will try to persist the attachments too
      puts "  ✅ Post '\#{post_2.title}' seeded successfully." # <--- escaped #
      post_2.categories << general unless post_2.categories.include?(general)
    else
      puts "  ❌ Failed to seed Post '\#{post_title_2}': \#{post_2.errors.full_messages.to_sentence}" # <--- escaped #
    end

    # Post 3
    post_title_3 = "Getting Started with Tailwind CSS in Rails"
    post_3 = Post.find_or_initialize_by(title: post_title_3)

    post_3.assign_attributes(
      subtitle: "Rapidly build beautiful UIs with a utility-first CSS framework.",
      published_at: 4.days.ago, # Even older
      admin: admin,
      meta_description: "Discover the power of Tailwind CSS for styling your Rails applications. Learn how to install and integrate it for fast UI development.",
      keywords: ["Tailwind CSS", "Rails", "frontend", "CSS", "UI development"],
      featured: false # NOT featured
    )
    post_3.content = <<~HTML
      <h2>What is Tailwind CSS?</h2>
      <p>Tailwind CSS is a utility-first CSS framework packed with classes like <code>flex</code>, <code>pt-4</code>, <code>text-center</code> and <code>rotate-90</code> that can be composed to build any design, directly in your markup.</p>
      <h3>Benefits for Rails Developers</h3>
      <ul>
        <li><strong>Speed:</strong> No more writing custom CSS; just combine utility classes.</li>
        <li><strong>Consistency:</b> Built-in design system ensures your UI is always on brand.</li>
        <li><strong>Maintainability:</b> Changes are local to the component, reducing unexpected side effects.</li>
      </ul>
      <p>Pairing Tailwind with Rails' Hotwire (Turbo, Stimulus) makes for an incredibly productive frontend development experience.</p>
    HTML

    # Attach images if desired (optional for non-featured posts)
    post_image_path_3 = Rails.root.join('app', 'assets', 'images', 'ruby-coffee.jpg')

    if File.exist?(post_image_path_3) && !post_3.image.attached?
      post_3.image.attach(io: File.open(post_image_path_3), filename: 'ruby-coffee.jpg', content_type: 'image/jpeg')
    end

    if post_3.save # Now save will try to persist the attachments too
      puts "  ✅ Post '\#{post_3.title}' seeded successfully." # <--- escaped #
      post_3.categories << uncategorized unless post_3.categories.include?(uncategorized)
    else
      puts "  ❌ Failed to seed Post '\#{post_title_3}': \#{post_3.errors.full_messages.to_sentence}" # <--- escaped #
    end

  RUBY

  say "#{INDENT}Seeding database...", :blue
  rails_command 'db:seed'
